### ISSUE TITLE
 Loop closure handling in Fuel Planner for exploration

### ISSUE THREAD

**Issue by zeeshanns** [SYSU-STAR/SOAR#1]
I have a query about managing pose jumps in exploration planning when using SLAM. Imagine a robot equipped with an exploration planner and a separate SLAM module. During exploration, if the robot returns to its starting point (Home), the SLAM algorithm will perform a loop closure. This action will result in a pose adjustment and updates to the SLAM map.

However, this might lead to inconsistencies in the Exploration Signed Distance Field (ESDF) map used by the exploration planner, which might not be updated in line with the SLAM adjustments. What is the best approach for the planner to handle these pose jumps after a SLAM loop closure? Should the ESDF map be reconstructed from the updated SLAM map sections? Additionally, how should the planner re-evaluate the frontiers after such updates?

**Comment by Zager-Zhang** [comment]
Thank for your sharing. The repository [Exploration-with-Global-Consistency](https://github.com/yzhangec/Exploration-with-Global-Consistency) incorporates loop closure into exploration. This work might be helpful for you.

**Comment by zeeshanns** [comment]
Thank you so much for the detailed response! I really appreciate your insights on managing pose jumps and loop closures in SLAM. It's helpful to know that repositories like Exploration-with-Global-Consistency can integrate loop closures into exploration, and I'll definitely look into that.

I also had a couple more questions regarding the FUEL exploration planner:

What adaptations would you recommend for the FUEL exploration planner when handling uneven terrain, where height variations and irregular surfaces may affect frontier detection and path planning?

Additionally, how would you approach the challenge of exploring large, unstructured, non-box-shaped environments, like tunnels or caves? In such cases, defining accurate exploration bounds might be difficult, and I’m concerned that inaccurate bounds could lead to excessive memory usage or inefficient exploration. What strategies would you suggest for managing these kinds of scenarios?

Thanks again for your valuable advice!
