### ISSUE TITLE
Issue facing during cakin_make

### ISSUE THREAD

**Issue by EhrazImam** [SYSU-STAR/SOAR#2]
make[1]: *** [CMakeFiles/Makefile2:5569: SOAR/src/simulator/local_sensing/CMakeFiles/opengl_render_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by Zager-Zhang** [comment]
Could you please provide more details about the error? It seems the local_sensing package, which is part of the MARSIM simulator, is causing issues. Perhaps there's a problem compiling the simulator correctly. @EhrazImam

**Comment by ning-zelin** [comment]
> make[1]: *** [CMakeFiles/Makefile2:5569: SOAR/src/simulator/local_sensing/CMakeFiles/opengl_render_node.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs....

I encountered the same issue. Are you compiling in the Anaconda environment? I solved it by running `conda deactivate` before `catkin_make`.

**Comment by Zager-Zhang** [comment]
Is your issue resolved now? @EhrazImam

**Comment by EhrazImam** [comment]
not yet will try and let you know
