### ISSUE TITLE
UnEven terrain, sloped surface, unstructured exploration space

### ISSUE THREAD

**Issue by zeeshanns** [SYSU-STAR/SOAR#3]
Thank you so much for this project! 
I also had a couple more questions regarding the FUEL exploration planner:
What adaptations would you recommend for the FUEL exploration planner when handling uneven terrain, where height variations and irregular surfaces may affect frontier detection and path planning?

Additionally, how would you approach the challenge of exploring large, unstructured, non-box-shaped environments, like tunnels or caves? In such cases, defining accurate exploration bounds might be difficult, and I’m concerned that inaccurate bounds could lead to excessive memory usage or inefficient exploration. What strategies would you suggest for managing these kinds of scenarios?

Thanks again for your valuable advice!

**Comment by Zager-Zhang** [comment]
These questions are great, but a bit complicated to describe in detail here. Feel free to add me on WeChat (13180320532) so we can discuss them further.
