### ISSUE TITLE
Issue with plan_env

### ISSUE THREAD

**Issue by wongsinglam** [SYSU-STAR/SOAR#4]
Hi, 

I am facing the issue while compiling the pack.

[ 28%] Building CXX object planner/plan_env/CMakeFiles/plan_env.dir/src/sdf_map.cpp.o
In file included from /home/shenglin/SOAR/src/planner/plan_env/src/sdf_map.cpp:4:
/home/shenglin/SOAR/src/planner/plan_env/include/plan_env/multi_map_manager.h:7:10: fatal error: plan_env/ChunkStamps.h: No such file or directory
    7 | #include <plan_env/ChunkStamps.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [planner/plan_env/CMakeFiles/plan_env.dir/build.make:63: planner/plan_env/CMakeFiles/plan_env.dir/src/sdf_map.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3890: planner/plan_env/CMakeFiles/plan_env.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Linking CXX executable /home/shenglin/SOAR/devel/lib/map_generator/map_pub
[ 28%] Built target map_pub
make: *** [Makefile:141: all] Error 2
Invoking "make -j2 -l2" failed

env: vmware vm
Ubuntu: 20.04

Thank you.

**Comment by wongsinglam** [comment]
Thank you for your reply. I tried to recompile again and again. Unfortunately, it seems not finishing compiling.

**Comment by wongsinglam** [comment]
Hi, Thank you so much. It works when increase the number of CPU as well as cores.

**Comment by Zager-Zhang** [comment]
I'm pleased to report that I've found the cause of the problem and have implemented a fix.  You should now be able to compile successfully with any number of CPU cores.  Thank you for your patience! @wongsinglam
