### ISSUE TITLE
 Plans for Porting FUEL Planner to ROS 2?

### ISSUE THREAD

**Issue by zeeshanns** [SYSU-STAR/SOAR#6]
Hi,

Are there any plans to port the FUEL planner to ROS 2? With ROS 2 becoming the standard for robotics, a ROS 2 version would greatly enhance its usability.
if not then, Could you provide any guidance or insights into challenges I might face?

**Comment by Zager-Zhang** [comment]
Hi there! Thanks for your interest in FUEL. We've been keeping an eye on the exciting developments with ROS 2 and its growing popularity in robotics. We certainly agree that a ROS 2 version of FUEL would be very useful for the community.

At this time, we don't have concrete plans to port FUEL to ROS 2, but we'll definitely consider ROS 2 as a potential platform for future development.
